# Generated by Django 5.2.6 on 2025-09-16 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
